clear all;

yalmip_path = '/home/jand271/rot/YALMIP-master';

load('hovland_et_al_model')
load('snapshots_of_hovland_el_al')

addpath('../../');
addpath(genpath(yalmip_path));

r = 1;

tic
V = buithanh(...
    eye(size(Ap,1)),...
    Ap, ...
    zeros(size(Ap,1),1), ...
    X,...
    r,...
    Cp,...
    1);
compute_time_s = toc;
W = V;
save(fullfile('output',['buithanh_rank_',num2str(r),'.mat']),...
    'W','V','compute_time_s');
