clear all;

load('hovland_et_al_model')
load('snapshots_of_hovland_el_al')

addpath('../../');

r_list = 1;...1:5;

for r = r_list
    tic
    V = buithanh(...
        eye(size(Ap,1)),...
        Ap, ...
        zeros(size(Ap,1),1), ...
        X,...
        r,...
        Cp,...
        0);
    compute_time_s = toc;
    W = V;
    save(fullfile('output',['buithanh_rank_',num2str(r),'.mat']),...
        'W','V','compute_time_s');
end
